# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"

    config.vm.network "private_network", ip: "192.168.100.3"

    config.vm.synced_folder ".", "/vagrant", type: "rsync"

    config.vm.provision "ansible" do |ansible|
        ansible.extra_vars = { ansible_ssh_user: "vagrant" }

        ansible.playbook = "site.yml"
        ansible.limit = "dbservers"
        ansible.inventory_path = "hosts"
        ansible.host_key_checking = false
    end
end